Traceback (most recent call last):
  File "C:\Users\pmarshal\Anaconda3\lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Users\pmarshal\Anaconda3\lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\pmarshal\Anaconda3\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Users\pmarshal\Anaconda3\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "C:\Users\pmarshal\Anaconda3\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "C:\Users\pmarshal\Anaconda3\lib\site-packages\nbclient\client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "C:\Users\pmarshal\Anaconda3\lib\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\pmarshal\Anaconda3\lib\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
precip = alt.Chart(meteo).mark_bar(color='green', size=16).encode(
    alt.X('datetime:T', title=None, axis=alt.Axis(labelAngle=90)),
    alt.Y('pc_3hr:Q', title = 'Precip-3hr (mm)')
).properties(width=800, height=150)


precip = precip + rules
precip
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mNameError[0m                                 Traceback (most recent call last)
Input [1;32mIn [4][0m, in [0;36m<cell line: 7>[1;34m()[0m
[0;32m      1[0m precip [38;5;241m=[39m alt[38;5;241m.[39mChart(meteo)[38;5;241m.[39mmark_bar(color[38;5;241m=[39m[38;5;124m'[39m[38;5;124mgreen[39m[38;5;124m'[39m, size[38;5;241m=[39m[38;5;241m16[39m)[38;5;241m.[39mencode(
[0;32m      2[0m     alt[38;5;241m.[39mX([38;5;124m'[39m[38;5;124mdatetime:T[39m[38;5;124m'[39m, title[38;5;241m=[39m[38;5;28;01mNone[39;00m, axis[38;5;241m=[39malt[38;5;241m.[39mAxis(labelAngle[38;5;241m=[39m[38;5;241m90[39m)),
[0;32m      3[0m     alt[38;5;241m.[39mY([38;5;124m'[39m[38;5;124mpc_3hr:Q[39m[38;5;124m'[39m, title [38;5;241m=[39m [38;5;124m'[39m[38;5;124mPrecip-3hr (mm)[39m[38;5;124m'[39m)
[0;32m      4[0m )[38;5;241m.[39mproperties(width[38;5;241m=[39m[38;5;241m800[39m, height[38;5;241m=[39m[38;5;241m150[39m)
[1;32m----> 7[0m precip [38;5;241m=[39m precip [38;5;241m+[39m [43mrules[49m
[0;32m      8[0m precip

[1;31mNameError[0m: name 'rules' is not defined
NameError: name 'rules' is not defined

